package Pojo;
// Generated Oct 8, 2019 12:39:21 PM by Hibernate Tools 4.3.1

import Model.DAOPizzaSubcriber;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblSubcriber generated by hbm2java
 */

@ManagedBean
public class TblSubcriber  implements java.io.Serializable {


     private Integer idSubcriber;
     private String email;
     private String phoneNumber;

    public TblSubcriber() {
    }

    public TblSubcriber(String email, String phoneNumber) {
       this.email = email;
       this.phoneNumber = phoneNumber;
    }
   
    public Integer getIdSubcriber() {
        return this.idSubcriber;
    }
    
    public void setIdSubcriber(Integer idSubcriber) {
        this.idSubcriber = idSubcriber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
//    public List<TblUser> getallrecords() {
//        DAOPizzaUser plg = new DAOPizzaUser();
//        List<TblUser> lPlg = plg.retrieveTblProduct();
//         return lPlg;
//    }
    
    public List<TblSubcriber>getRec(){
        DAOPizzaSubcriber kry = new DAOPizzaSubcriber();
        List<TblSubcriber> lKry = kry.retrieveKary();
        return lKry;
    }
   

        public void save(){
        DAOPizzaSubcriber kr = new DAOPizzaSubcriber();
        kr.addSubcriber(this);
    }




}


