package Pojo;
// Generated Oct 8, 2019 12:39:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.faces.bean.ManagedBean;
import Model.DAOPizzaTransaction;
import java.util.List;
/**
 * TblTransaction generated by hbm2java
 */

@ManagedBean
public class TblTransaction  implements java.io.Serializable {


     private Integer idTransaction;
     private int idUser;
     private int idPizzaProduct;
     private String name;
     private String pizzaName;
     private int price;
     private int qty;
     private int totalPrice;
     private String address;
     private String dateOfPurchase;

    public TblTransaction() {
    }

    public TblTransaction(int idUser, int idPizzaProduct, String name, String pizzaName, int price, int qty, int totalPrice, String address, String dateOfPurchase) {
       this.idUser = idUser;
       this.idPizzaProduct = idPizzaProduct;
       this.name = name;
       this.pizzaName = pizzaName;
       this.price = price;
       this.qty = qty;
       this.totalPrice = totalPrice;
       this.address = address;
       this.dateOfPurchase = dateOfPurchase;
    }
   
    public Integer getIdTransaction() {
        return this.idTransaction;
    }
    
    public void setIdTransaction(Integer idTransaction) {
        this.idTransaction = idTransaction;
    }
    public int getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }
    public int getIdPizzaProduct() {
        return this.idPizzaProduct;
    }
    
    public void setIdPizzaProduct(int idPizzaProduct) {
        this.idPizzaProduct = idPizzaProduct;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPizzaName() {
        return this.pizzaName;
    }
    
    public void setPizzaName(String pizzaName) {
        this.pizzaName = pizzaName;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getQty() {
        return this.qty;
    }
    
    public void setQty(int qty) {
        this.qty = qty;
    }
    public int getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(int totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getDateOfPurchase() {
        return this.dateOfPurchase;
    }
    
    public void setDateOfPurchase(String dateOfPurchase) {
        this.dateOfPurchase = dateOfPurchase;
    }
    
    public List<TblTransaction>getRec(){
        DAOPizzaTransaction kry = new DAOPizzaTransaction();
        List<TblTransaction> lKry = kry.retrieveKary();
        return lKry;
    }
   

        public void save(){
        DAOPizzaTransaction kr = new DAOPizzaTransaction();
        kr.addTransaction(this);
    }




}


