package Pojo;
// Generated Oct 8, 2019 12:39:21 PM by Hibernate Tools 4.3.1

import Model.DAOPizzaLoginUser;
import Model.DAOPizzaUser;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblUser generated by hbm2java
 */

@ManagedBean
public class TblUser  implements java.io.Serializable {


     private Integer idUser;
     private String firstname;
     private String lastname;
     private String email;
     private String password;
     private String address;
     private String phoneNumber;

    public TblUser() {
    }

    public TblUser(String firstname, String lastname, String email, String password, String address, String phoneNumber) {
       this.firstname = firstname;
       this.lastname = lastname;
       this.email = email;
       this.password = password;
       this.address = address;
       this.phoneNumber = phoneNumber;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    public String getbyid(int idUser2) {
        DAOPizzaUser plg = new DAOPizzaUser();

        List<TblUser> lPlg = plg.getbyId(idUser2);
        if (!lPlg.isEmpty()) {
            idUser = lPlg.get(0).idUser;
            firstname = lPlg.get(0).firstname;
            lastname = lPlg.get(0).lastname;
            email = lPlg.get(0).email;
            password = lPlg.get(0).password;
            address = lPlg.get(0).address;
            phoneNumber = lPlg.get(0).phoneNumber;
            return "edituser";
        }
//        errorU = true;
        return "edituser";
    }
    
    public List<TblUser> getallrecords() {
        DAOPizzaUser plg = new DAOPizzaUser();
        List<TblUser> lPlg = plg.retrieveTblProduct();
         return lPlg;
    }
    
    public String update() {
        DAOPizzaUser usr = new DAOPizzaUser();
        List<TblUser>lPlg = usr.getbyId(idUser);
        if (!lPlg.isEmpty()) {
        usr.updateUser(this);
        }
        return "user-table";
     
    }
    
    public List<TblUser>getRec(){
        DAOPizzaUser kry = new DAOPizzaUser();
        List<TblUser> lKry = kry.retrieveKary();
        return lKry;
    }
   
    public void delete1(int idUser) {
        DAOPizzaUser kry = new DAOPizzaUser();
        List<TblUser>lPlg = kry.getbyId(idUser);
        if (!lPlg.isEmpty()) {
            kry.deleteUser(idUser);
        }
    }

    
        public String save(){
        DAOPizzaUser kr = new DAOPizzaUser();
        kr.addUser(this);
        return "login";
    }
        
        public String validasiUser() {
        DAOPizzaLoginUser uDao = new DAOPizzaLoginUser();
        List<TblUser> us = uDao.getBy(email, password);
        if (us != null) {
            email = us.get(0).email;
            password = us.get(0).password;
           
            return "order";
        } 
            return "order";

    }

}


